### ISSUE TITLE
Can't import audio 

### ISSUE THREAD

**Issue by MegaTheLEGEND** [potatosalad775/eqTrainer#1]
When I try to add audio to my playlist it won't let me set the timing of the file. I can't set the start time after the end time, but I can't set the end time before the start time. I get those errors every time I try to set the file times.

I am on Android 14.

**Comment by potatosalad775** [comment]
@MegaTheLEGEND Hello.
Sorry for being this late.

I've prepared an pre-release version of eqTrainer for Android, which should fix the issue you've mentioned.

Can you try out the [APK file attached to this link](https://github.com/potatosalad775/eqTrainer/releases/tag/v2.2.2)? Let me know if the issue still persists.

**Comment by MegaTheLEGEND** [comment]
Yep seems to work as expected now. Although the audio playback seems a bit choppy in my limited testing.

**Comment by potatosalad775** [comment]
Thanks for checking it out. I'm planning to improve the playback performance in the next update. Thank you!
